# CLEAN codemagic.yaml - NO syntax errors
workflows:
  ios-simple:
    name: Simple iOS Build
    environment:
      flutter: "3.38.4"
      xcode: 26.2
    
    scripts:
      - name: Build iOS
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign
          
          echo "=== Build completed ==="
          if [ -d "build/ios/iphoneos" ]; then
            ls -la build/ios/iphoneos/
            echo "App file is ready!"
          else
            echo "Build directory not found"
            find . -name "*.app" 2>/dev/null
          fi
    
    artifacts:
      - build/ios/iphoneos/Runner.app
    
    publishing:
      email:
        recipients:
          - your-email@example.com
