workflows:
  ios-auto-sign:
    name: iOS with Auto-Signing
    environment:
      flutter: "3.38.4"
      xcode: 26.2
      # ENABLE automatic code signing
      ios_signing: 
        distribution_type: ad_hoc  # or development
      
    scripts:
      - name: Build with Signing
        script: |
          flutter clean
          flutter pub get
          
          # Build WITH code signing (remove --no-codesign)
          flutter build ipa --release
          
          echo "=== Signed IPA created ==="
          ls -la build/ios/ipa/
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - your-email@example.com
