workflows:
  ios-with-ipa:
    name: Build iOS with IPA
    environment:
      xcode: 26.2
      flutter: 3.38.4
      cocoapods: default
      
      groups:
        - app_store_credentials  # If you have certificates
    
    scripts:
      - name: Build iOS Archive
        script: |
          flutter clean
          flutter pub get
          
          # Build the archive (.xcarchive)
          flutter build ios --release --no-codesign
          
          echo "=== Archive created at ==="
          find build -name "*.xcarchive" -type d
          
      - name: Create IPA from Archive
        script: |
          # Create export_options.plist if not exists
          if [ ! -f "ios/export_options.plist" ]; then
            cat > ios/export_options.plist << EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>method</key>
                <string>development</string>
                <key>teamID</key>
                <string>XXXXXXXXXX</string>  # Your team ID or leave empty
            </dict>
            </plist>
            EOF
          fi
          
          # Convert xcarchive to IPA
          xcodebuild -exportArchive \
            -archivePath "build/ios/archive/Runner.xcarchive" \
            -exportOptionsPlist "ios/export_options.plist" \
            -exportPath "build/ios/ipa" \
            -allowProvisioningUpdates
          
          echo "=== IPA created at ==="
          ls -la build/ios/ipa/
    
    artifacts:
      # BOTH formats
      - build/ios/ipa/*.ipa
      - build/ios/archive/Runner.xcarchive
      - build/ios/iphoneos/Runner.app
    
    publishing:
      email:
        recipients:
          - your-email@example.com
