workflows:
  ios-test:
    name: iOS Test Build
    environment:
      flutter: "stable"
      ios_signing:
        distribution_type: development
        bundle_identifier: "com.personal.myexpenseapp"
    
    scripts:
      - name: Debug Current Bundle ID
        script: |
          echo "=== Checking current bundle ID ==="
          
          # Check Info.plist
          if [ -f "ios/Runner/Info.plist" ]; then
            echo "Info.plist CFBundleIdentifier:"
            plutil -extract CFBundleIdentifier raw ios/Runner/Info.plist || echo "Not found in Info.plist"
          fi
          
          # Check Xcode project
          if [ -f "ios/Runner.xcodeproj/project.pbxproj" ]; then
            echo -e "\nXcode PRODUCT_BUNDLE_IDENTIFIER:"
            grep -n "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj || echo "Not found in project"
          fi
          
          # Check Flutter config
          echo -e "\nChecking pubspec.yaml..."
          if [ -f "pubspec.yaml" ]; then
            grep -i "name:" pubspec.yaml | head -1
          fi
