workflows:
  ios-test:
    name: iOS Test Build
    environment:
      flutter: "stable"
      ios_signing:
        distribution_type: development
        bundle_identifier: "com.personal.myexpenseapp"  # What we'll sign with
    
    scripts:
      - name: Fix Bundle ID Everywhere
        script: |
          echo "Changing bundle ID from com.example.myexperience to com.personal.myexpenseapp"
          
          # 1. Update Info.plist
          plutil -replace CFBundleIdentifier -string "com.personal.myexpenseapp" ios/Runner/Info.plist
          
          # 2. Update Xcode project
          sed -i '' 's/com\.example\.myexperience/com.personal.myexpenseapp/g' ios/Runner.xcodeproj/project.pbxproj 2>/dev/null || true
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*;/PRODUCT_BUNDLE_IDENTIFIER = com.personal.myexpenseapp;/g' ios/Runner.xcodeproj/project.pbxproj 2>/dev/null || true
          
          # 3. Also check for any other references
          grep -r "com.example.myexperience" ios/ || echo "No other references found"
          
          echo "✅ Bundle ID updated everywhere"
      
      - name: Verify Changes
        script: |
          echo "=== Verifying bundle ID ==="
          CURRENT_ID=$(plutil -extract CFBundleIdentifier raw ios/Runner/Info.plist)
          echo "Info.plist now has: $CURRENT_ID"
          
          if [ "$CURRENT_ID" != "com.personal.myexpenseapp" ]; then
            echo "❌ Error: Bundle ID not updated correctly!"
            exit 1
          fi
      
      - name: Build IPA
        script: |
          flutter build ipa --release --export-method development
          echo "✅ Build complete"
    
    artifacts:
      - build/ios/ipa/*.ipa
