workflows:
  ios-test:
    name: iOS Test Build
    environment:
      flutter: "stable"
      ios_signing:
        distribution_type: development
        automatic: true
    
    scripts:
      - name: Build
        script: |
          flutter build ipa --release --export-method development
    
    artifacts:
      - build/ios/ipa/*.ipa
