workflows:
  ios-test:
    name: iOS 7-Day Test Build
    environment:
      flutter: "stable"
      xcode: latest
      ios_signing:
        distribution_type: development
        bundle_identifier: "com.example.myexperience"  # ← ADD THIS
    
    scripts:
      - name: Set Bundle ID in Info.plist
        script: |
          # Make sure Info.plist matches
          plutil -replace CFBundleIdentifier -string "com.personal.myexpenseapp" ios/Runner/Info.plist
          echo "✅ Bundle ID updated in Info.plist"
      
      - name: Build IPA
        script: |
          flutter build ipa --release --export-method development
          echo "✅ IPA built for 7-day testing"
    
    artifacts:
      - build/ios/ipa/*.ipa
