workflows:
  ios-simple:
    environment:
      flutter: stable
      ios_signing:
        distribution_type: development
    
    scripts:
      - flutter build ipa --release --export-method development
    
    artifacts:
      - build/ios/ipa/*.ipa
